version: "3"

services:
  hippocampus:
    image: brenoreissan/hippocampus:local
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
